#!/usr/bin/env python

"""
create the cam library
"""
#pylint: disable=multiple-imports, wrong-import-position, wildcard-import
#pylint: disable=unused-wildcard-import, bad-whitespace, too-many-locals
#pylint: disable=invalid-name
import sys, os, filecmp, shutil, imp

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")

_LIBDIR = os.path.join(_CIMEROOT, "scripts", "Tools")
sys.path.append(_LIBDIR)

from standard_script_setup import *
from CIME.case import Case
from CIME.utils import run_cmd, expect
from CIME.buildlib import parse_input
from CIME.build import get_standard_makefile_args

logger = logging.getLogger(__name__)

###############################################################################
def _build_codon_lib(srcroot, stem, subdir="physics/cam"):
###############################################################################

    codon_src = os.path.join(srcroot, "components", "cam", "src", subdir,
                             "{}_codon.py".format(stem))
    if not os.path.isfile(codon_src):
        return

    codon_lib = os.path.join(srcroot, "components", "cam", "src", subdir,
                             "lib{}_codon.so".format(stem))
    codon_bin = shutil.which("codon")
    if codon_bin is None:
        codon_bin = os.path.join(os.path.expanduser("~"), ".codon", "bin", "codon")

    expect(os.path.isfile(codon_bin),
           "Unable to find Codon compiler for {}_codon.py".format(stem))

    cmd = "{} build -release -lib --relocation-model=pic --fp-contract=off {} -o {}" \
        .format(codon_bin, codon_src, codon_lib)
    rc, out, err = run_cmd(cmd)
    logger.info("%s: \n\n output:\n %s \n\n err:\n\n%s\n", cmd, out, err)
    expect(rc == 0, "Command %s failed with rc=%s" % (cmd, rc))

###############################################################################
def _build_cam():
###############################################################################

    caseroot, libroot, bldroot = parse_input(sys.argv)

    with Case(caseroot, read_only=False) as case:

        srcroot = case.get_value("SRCROOT")
        #-------------------------------------------------------
        # Call cam's buildcpp
        #-------------------------------------------------------
        cmd = os.path.join(os.path.join(srcroot, "components", "cam",
                                        "cime_config", "buildcpp"))
        logger.info("     ...calling cam buildcpp to set build time options")
        try:
            mod = imp.load_source("buildcpp", cmd)
            cam_cppdefs = mod.buildcpp(case)
        except:
            raise

    with Case(caseroot) as case:

        casetools = case.get_value("CASETOOLS")
        srcroot = case.get_value("SRCROOT")
        gmake_j = case.get_value("GMAKE_J")
        gmake = case.get_value("GMAKE")
        mach = case.get_value("MACH")

        _build_codon_lib(srcroot, "rayleigh_friction")
        _build_codon_lib(srcroot, "dadadj")
        _build_codon_lib(srcroot, "qneg3")
        _build_codon_lib(srcroot, "qneg4")
        _build_codon_lib(srcroot, "radheat")
        _build_codon_lib(srcroot, "aoa_tracers")
        _build_codon_lib(srcroot, "tracers")
        _build_codon_lib(srcroot, "qbo")
        _build_codon_lib(srcroot, "flux_avg")
        _build_codon_lib(srcroot, "cam_diagnostics")
        _build_codon_lib(srcroot, "vertical_diffusion")
        _build_codon_lib(srcroot, "chem_surfvals")
        _build_codon_lib(srcroot, "aero_model")
        _build_codon_lib(srcroot, "chemistry")
        _build_codon_lib(srcroot, "gw_drag")
        _build_codon_lib(srcroot, "mo_lightning")
        _build_codon_lib(srcroot, "microp_driver")
        _build_codon_lib(srcroot, "macrop_driver")
        _build_codon_lib(srcroot, "stratiform")
        _build_codon_lib(srcroot, "convect_shallow")
        _build_codon_lib(srcroot, "convect_deep")
        _build_codon_lib(srcroot, "conv_water")
        _build_codon_lib(srcroot, "physpkg")
        _build_codon_lib(srcroot, "prim_subcycle_q_update", "dynamics/se")

        #-------------------------------------------------------
        # Filepath is created in caseroot/camconf by the call
        # to buildcpp - this needs to be copied to bldroot
        #-------------------------------------------------------
        filesrc = os.path.join(caseroot, "Buildconf", "camconf", "Filepath")
        filedst = os.path.join(bldroot, "Filepath_tmp")
        shutil.copy(filesrc, filedst)

        filedst     = os.path.join(bldroot, "Filepath")
        filedst_tmp = os.path.join(bldroot, "Filepath_tmp")
        if os.path.isfile(filedst):
            if not filecmp.cmp(filedst_tmp, filedst):
                shutil.move(filedst_tmp, filedst)
        else:
            shutil.move(filedst_tmp, filedst)

        #-------------------------------------------------------
        # build the library
        #-------------------------------------------------------
        complib  = os.path.join(libroot, "libatm.a")
        makefile = os.path.join(casetools, "Makefile")

        cmd = "{} complib -j {} MODEL=cam COMPLIB={} -f {} {} " \
            .format(gmake, gmake_j, complib, makefile, get_standard_makefile_args(case))
        if cam_cppdefs:
            cmd += " USER_CPPDEFS='{}'".format(cam_cppdefs)

        rc, out, err = run_cmd(cmd)
        logger.info("%s: \n\n output:\n %s \n\n err:\n\n%s\n", cmd, out, err)
        expect(rc == 0, "Command %s failed with rc=%s" % (cmd, rc))

###############################################################################

if __name__ == "__main__":
    _build_cam()
